INSERT INTO `users` (`password`, `last_login`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`, `avatar`, `description`) VALUES
('pbkdf2_sha256$120000$kRj0sglysnXt$X4jb6hVprJDwnNOABM9aSMiQxf5JLbCkXkKQkWeIKI8=', NULL, 1, 'root', '', '', '', 1, 1, NOW(), 'avatars/root.jpg', 'System administrator');

INSERT INTO `game` (`id`, `name`, `description`, `platform`, `game_image`) VALUES
(1, 'The Legend of Zelda: Breath of the Wild', 'The Legend of Zelda: Breath of the Wild (яп. ゼルダの伝説 ブレス オブ ザ ワイルド Дзэруда но Дэнсэцу Бурэсу обу дза Вайрудо) — приключенческая видеоигра, разработанная и выпущенная Nintendo для консолей Nintendo Switch и Wii U. Это 19-й релиз в серии The Legend of Zelda. История начинается в Хайруле и связана с постоянным протагонистом серии — Линком, потерявшим память. Он пробуждается от 100-летнего сна, услышав таинственный голос, который ведёт его к победе над Бедствием Ганоном.', 13, 'game_images/Zelda.jpeg'),
(2, 'Super Mario Party', 'Super Mario Party is a party video game developed by NDcube and published by Nintendo. An entry in the Mario Party series, it was released for Nintendo Switch on 5 October 2018 and sold 1.5 million copies by the end of the month, making it one of the system\'s best-selling games.', 13, 'game_images/super_mario_party.jpg'),
(3, 'Diablo III', 'Diablo III — компьютерная игра жанра Action RPG, разработанная компанией Blizzard Entertainment, для платформ Microsoft Windows, Mac OS X, PlayStation 3, PlayStation 4, Xbox 360, Xbox One и Switch. Игра содержит также элементы жанров Action/RPG и dungeon crawl.\r\n\r\nИгра является частью серии игр Diablo и прямым продолжением Diablo II. Действие игры, как и в предыдущих частях серии, происходит в мире тёмного фэнтези, называемом Санктуарий (англ. Sanctuary — святилище, убежище). События развиваются вокруг борьбы армии Небес с армией Преисподней за мир Санктуария. Персонажи игроков не являются прямыми последователями этих фракций, однако тяготеют к силам Небес, так как армии Преисподней стремятся поработить и разрушить Санктуарий — их родной мир.', 13, 'game_images/diablo.jpg'),
(4, 'The Legend of Zelda: The Minish Cap', 'The Legend of Zelda: The Minish Cap (яп. ゼルダの伝説 ふしぎのぼうし Дзэруда но Дэнсэцу Фусиги но Бо:си) — видеоигра из серии The Legend of Zelda, разработанная компанией Flagship для Game Boy Advance и выпущенная в 2004 году в Японии и Европе и в 2005 — в Северной Америке. The Minish Cap является сюжетным продолжением игр The Legend of Zelda: A Link to the Past and Four Swords (переизданная на GBA The Legend of Zelda: A Link to the Past) и The Legend of Zelda: Four Swords Adventures.', 7, 'game_images/minish_cap.jpg'),
(5, 'Super Smash Bros. Ultimate', 'Super Smash Bros. Ultimate — компьютерная игра в жанре файтинга из серии Super Smash Bros., разрабатываемая компаниями Bandai Namco Studios и Sora Ltd. Игра была выпущена для игровой приставки Nintendo Switch 7 декабря 2018 года.', 13, 'game_images/supersmash.jpg'),
(6, 'Mario Kart 8 Deluxe', 'Mario Kart 8 (яп. マリオカート8 Марио Ка:то Эито) — компьютерная игра в жанре автосимулятор, восьмая в серии Mario Kart. Выход игры состоялся 29 мая 2014 года в Японии, 30 мая 2014 года в Европе и Северной Америке и 31 мая 2014 года в Австралии эксклюзивно для Wii U.\r\n\r\n28 апреля 2017 года вышла улучшенная версии игры для Nintendo Switch, которая получила название Mario Kart 8 Deluxe.', 13, 'game_images/marikart.jpeg'),
(7, 'Rayman Legends: Definitive edition', 'Rayman Legends — компьютерная игра в жанре платформер из игровой серии Rayman, рассказывающая о приключениях Рэймана и его друзей, является прямым продолжением Rayman Origins. Первоначально игра задумывалась как эксклюзив для Wii U, однако, позднее было принято решение выпустить её и на других ключевых платформах: Microsoft Windows, PlayStation 3 и Xbox 360, а позднее и на PlayStation 4 и Xbox One. Rayman Legends была издана 29 августа 2013 года в Австралии, 30 августа в Европе, и 3 сентября в США. Позже, Ubisoft подтвердила информацию о выпуске игры на консолях нового поколения, дата релиза — 25 февраля 2014. Русской локализацией занималась компания Новый диск — игра вышла полностью на русском языке.', 13, 'game_images/rayman.png'),
(8, 'The Legend of Zelda: Ocarina of Time', 'The Legend of Zelda: Ocarina of Time (яп. ゼルダの伝説 時のオカリナ Дзэруда но Дэнсэцу Токи но Окарина) — приключенческая видеоигра, разработанная и изданная Nintendo для игровой консоли Nintendo 64 как очередная часть популярной серии The Legend of Zelda. За ней последовал сиквел The Legend of Zelda: Majora`s Mask. Признана лучшей видеоигрой за всю историю игровой индустрии.', 11, 'game_images/ocarina_of_time.jpg'),
(9, 'LEGO Star Wars II: The Original Trilogy', 'LEGO Star Wars II: The Original Trilogy — компьютерная игра, основанная на серии игрушек LEGO по мотивам вселенной «Звёздных войн». Действие игры разворачивается в течение оригинальной трилогии (Новая надежда, Империя наносит ответный удар, Возвращение джедая). Игра вышла 12 сентября 2006 года, её действие разворачивается через 19 лет после установления Первой Галактической Империи. \r\nНесмотря на то, что трилогия LEGO Star Wars позиционировалась, как игра для детей, она снискала славы и у более взрослых игроков. По миру было продано более 8,2 млн копий игры (по состоянию на февраль 2009).', 7, 'game_images/star_wars_lego.jpg'),
(10, 'Into the Breach', 'Into the Breach — компьютерная игра в жанре пошаговой стратегии, разработанная и выпущенная американской студией Subset Games для Microsoft Windows, macOS и Nintendo Switch в 2018 году. В Into the Breach игрок управляет отрядом огромных боевых машин-мехов, защищающих города от нашествия гигантских монстров-кайдзю. Действие игры происходит на небольших, намеренно минималистичных картах, напоминающих шахматную доску, и игрок должен добиться победы в каждом сражении за несколько раундов и не допустить уничтожения городов, находящихся на некоторых клетках. Планируемые ходы противника отображаются на экране, и важную роль в игре играет позиционирование фигур — многие атаки и способности позволяют сдвигать фигуры противника на одну или несколько клеток.', 13, 'game_images/SQ_NSwitchDS_IntoTheBreach.jpg'),
(11, 'FIFA 19', 'FIFA 19 — 26-я футбольная игра из серии игр FIFA, разработанная для платформ Windows, Nintendo Switch, PlayStation 4, PlayStation 3, Xbox One и Xbox 360. Игра выпущена компанией Electronic Arts 28 сентября 2018. Лицом игры является футболист Ювентуса (на момент выхода игры) и сборной Португалии Криштиану Роналду.', 13, 'game_images/fifa.jpeg');

INSERT INTO `game_owner` (`id`, `game_id`, `profile_id`) VALUES
(1, 1, 1),
(2, 2, 1),
(3, 3, 1),
(4, 4, 1),
(5, 5, 1),
(6, 6, 1),
(7, 7, 1),
(8, 8, 1),
(9, 9, 1),
(10, 10, 1),
(11, 11, 1);
